POST http://localhost:8080/shorten
Content-Type: application/json

{
  "url": "https://www.google.com"
}

###
GET http://localhost:8080/2OB91xD
User-Agent: test 

###
GET http://localhost:8080/invalid123

###
POST http://localhost:8080/shorten
Content-Type: application/json

{
  "url": "https://github.com",
  "customAlias": "github"
}

###
GET http://localhost:8080/github