spring.application.name=Url-Shortner

# Render PostgreSQL Database Configuration

server.port=9090
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate JPA Configuration
spring.jpa.hibernate.ddl-auto=update

# Show SQL Queries in the Console (Optional)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret =${JWT_SECRET}
jwt.expiration=172800000

frontend.url= https://url-shortener-beige-phi.vercel.app

# Redis Cache Configuration
spring.cache.type=${CACHE_TYPE:simple}
spring.data.redis.url=${REDIS_URL:}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED:true}
spring.data.redis.timeout=${REDIS_TIMEOUT:2s}

# Default Cache TTL
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
